
# https://github.com/thundergolfer/thundergolfer.github.io/blob/main/_config.yml 
# https://github.com/thundergolfer/thundergolfer.github.io

# Site settings
title: Trevor Hall
author: Trevor Hall
description: "It's all nonsense"
baseurl: ""
url: "https://hallta.com"
date_format: "%b %-d, %Y"
exclude: ["env", ".gitignore", "README.md", "CNAME"]
google_tag_manager: G-7Y6DQFCVZT

show_related_posts: true
show_post_footers: true
show_subscribe_cta: true
show_social_icons: false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: 
stackoverflow_id:
twitter_username:
linkedin_username:

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: pretty
paginate: 12
paginate_path: "/blog/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true